#pragma once

//Running modes
#define VISUAL_MODE true
#define GRAPHICAL true
#define INIT_MSG false

//Cam controls
#define CAM_FORWARD GLFW_KEY_W
#define CAM_LEFT GLFW_KEY_A
#define CAM_BACKWARD GLFW_KEY_S
#define CAM_RIGHT GLFW_KEY_D
#define CAM_UP GLFW_KEY_SPACE
#define CAM_DOWN GLFW_KEY_LEFT_CONTROL
#define CAM_BOOST GLFW_KEY_LEFT_SHIFT

#define CAM_ORTHO GLFW_KEY_O
#define CAM_INFO GLFW_KEY_APOSTROPHE

#define CAM_LOOK_DOWN GLFW_KEY_KP_2
#define CAM_LOOK_RIGHT GLFW_KEY_KP_6
#define CAM_LOOK_DIAGONAL GLFW_KEY_KP_3

//Simulation controls
#define SIM_STEP GLFW_KEY_N
#define SIM_TIME_FORWARD GLFW_KEY_L
#define SIM_TIME_BACKWARD GLFW_KEY_J
#define SIM_TIME_JUMP GLFW_KEY_I
#define SIM_SHOW_CCA GLFW_KEY_K
#define SIM_SHOW_PREVIOUS_CA GLFW_KEY_LEFT
#define SIM_SHOW_NEXT_CA GLFW_KEY_RIGHT
#define SIM_SHOW_ONLY_CCA GLFW_KEY_C
#define SIM_VIEW_ALL_ORBITS GLFW_KEY_G
#define SIM_SCHEMATIC GLFW_KEY_SLASH